### ISSUE TITLE
Separate mappings for open with quickfix focused

### ISSUE THREAD

**Issue by qsvui** [yssl/QFEnter#12]
Is it possible to create different mappings for opening from the quickfix window, but keeping focus on the quickfix window? I know there is the g:qfenter_keep_quickfixfocus variable, but this seems to override the default open behavior of changing focus to the window with the error.

I became interested by some quickfix features of the [ack.vim](https://github.com/mileszs/ack.vim#keyboard-shortcuts) plugin. Unfortunately, the mappings for this only seem to apply to a quickfix window with ack results and they go away after you close the quickfix window.

**Comment by yssl** [comment]
Could you let me know more specifically, in which use case you feel g:qfenter_keep_quickfixfocus is not enough?
Actually, QFEnter already has 12 global variables for key mapping so I don't think it's a good idea to double them with keep focus or not.
I'm sorry about late reply.

**Comment by qsvui** [comment]
Well, sometimes I may want to open a quickfix item and have the focus change to the window with the error. But other times, I may want to have the focus kept on the quickfix window so I can quickly skim through the quickfix items. I just thought it would be convenient to have different mappings available for these cases.

**Comment by yssl** [comment]
It makes sense. I'm gonna start to consider how to meet the requirement while minimizing confliction with current structure. I'll give you feedback soon.

**Comment by yssl** [comment]
Sorry for late update.
I've fully changed the key mapping system of QFEnter to meet requirements for more flexible configuration. I believe this can satisfy your needs.
Of course, the old way still can be used with deprecation notification messages until version 2.4.0.
Please test the update and report bugs and other opinions.
