### ISSUE TITLE
The location list should be open when open an item under cursor in a new tab

### ISSUE THREAD

**Issue by QMonkey** [yssl/QFEnter#14]
I have set this option:
```vim
let g:qfenter_enable_autoquickfix = 1
```

Therefore,  when 'open in a new tab' command is executed inside the location list, the location list window should be opened automatically rather than the quickfix window.

I have a solution. How about replacing the line [258](https://github.com/yssl/QFEnter/blob/master/autoload/QFEnter.vim#L258) with the code below?

```vim
if isloclist
	exec modifier 'lopen'
else
	exec modifier 'copen'
endif
```

**Comment by yssl** [comment]
Definitely right. Why don't you send a pull request and be a contributor of QFEnter?

**Comment by QMonkey** [comment]
#15 I have made a pull request. :)
