### ISSUE TITLE
"No location list error" when using topen

### ISSUE THREAD

**Issue by electric-ladyland** [yssl/QFEnter#18]
This plugin is so valuable. Just one problem, I have mapped `topen` to `<C-t>`, and when I use it, I always get this error:

```
Error detected while processing function QFEnter#OpenQFItem[8]..<SNR>99_OpenQFItem[48]..<SNR>99_ExecuteCC:
line    7:
E776: No location list
Error detected while processing function QFEnter#OpenQFItem[8]..<SNR>99_OpenQFItem:
line   84:
E776: No location list
```

I narrowed it down to this plugin: [vim-quit-if-only-quickfix-buffer-left](https://github.com/now/vim-quit-if-only-quickfix-buffer-left/blob/master/plugin/now/quit-if-only-quickfix-buffer-left.vim) which closes windows if only a quickfix remains. This is also really valuable.

Any way to make them play nicely together?

**Comment by yssl** [comment]
I cannot reproduece the error.
Could you tell me more about how to reproduce the situation?

**Comment by yssl** [comment]
Closing the issue due to lack of response.
