### ISSUE TITLE
exclude nerdtree window。

### ISSUE THREAD

**Issue by lsaint** [yssl/QFEnter#20]
If previously focused window is a needtree window, can we make an exception?  I  would like to  keep needtree windows  static.

**Comment by yssl** [comment]
That's a good idea :)
I've uploaded the version 2.4.0 that supports an option to prevent opening items in windows of certain filetypes.
You can refer https://github.com/yssl/QFEnter#preventing-opening-items-in-windows-of-certain-filetypes.
Sorry for the late update.
