### ISSUE TITLE
open_keep mapping doesn't appear to work

### ISSUE THREAD

**Issue by levouh** [yssl/QFEnter#21]
### Issue

In my `~/.vimrc`:

```
let g:qfenter_keymap = {}
let g:qfenter_keymap.open_keep = ['<CR>']
let g:qfenter_keymap.vopen_keep = ['<Leader><CR>']
let g:qfenter_keymap.hopen_keep = ['<Leader><Space>']
```

The mappings for `vopen_keep` and `hopen_keep` work just fine, but `open_keep` does not. Am I doing something wrong here?

### Debug Information

While in a `qf` window, `:nmap` outputs:

```
n  <CR>        *@:call QFEnter#OpenQFItem("o","c","0",0)<CR>
n  ,<Tab>      *@:call QFEnter#OpenQFItem("t","c","0",0)<CR>
n  ,<Space>    *@:call QFEnter#OpenQFItem("h","c","1",0)<CR>
n  ,<CR>       *@:call QFEnter#OpenQFItem("v","c","1",0)<CR>
```

so it seems that the mapping isn't getting setup correctly.

`:echo g:qfenter_keymap` outputs:

```
{
'vopen': ['<Leader><CR>'], 
'hopen': ['<Leader><Space>'],
'vopen_keep': ['<Leader><CR>'], 
'topen': ['<Leader><Tab>'], 
'open_keep': ['<CR>'],
'open': ['<CR>', '<2-LeftMouse>'],
'hopen_keep': ['<Leader><Space>']
}
```

so it appears the `hopen_keep` and `vopen_keep` are working due to the fact that they got mapped after their associated non-`keep` commands?

### Temporary Solution

Instead of what I've mentioned above, use:

```
let g:qfenter_keymap = {}
let g:qfenter_keymap.open = ['']
let g:qfenter_keymap.open_keep = ['<CR>']
let g:qfenter_keymap.vopen_keep = ['<Leader><CR>']
let g:qfenter_keymap.hopen_keep = ['<Leader><Space>']
```

**Comment by yssl** [comment]
Thanks for the detailed report and sorry for my late reply.
I've uploaded the version 2.4.0, in which the code for the process from shortcut key input to final action has largely been changed.

Using the following setting in 2.4.0 does not reproduce the reported problem. I guess that some hidden problems has been probably fixed during the code refactoring. 
```
let g:qfenter_keymap = {}
let g:qfenter_keymap.open_keep = ['<CR>']
let g:qfenter_keymap.vopen_keep = ['<Leader><CR>']
let g:qfenter_keymap.hopen_keep = ['<Leader><Space>']
```

Now  my `:nmap` outputs for the above setting in quickfix windows are as follows:
```
n  <CR>        *@:call QFEnter#OpenQFItem("QFEnter#GetTabWinNR_Open","cc","1",0)<CR>                                                                                                                               
n  ,<Space>    *@:call QFEnter#OpenQFItem("QFEnter#GetTabWinNR_HOpen","cc","1",0)<CR>                                                                                                                              
n  ,<CR>       *@:call QFEnter#OpenQFItem("QFEnter#GetTabWinNR_VOpen","cc","1",0)<CR>          
```

Please check and reopen the issue if you still have such a problem.
