### ISSUE TITLE
Auto-close quickfix list after an item has been selected

### ISSUE THREAD

**Issue by minhduc0711** [yssl/QFEnter#25]
I prefer the quickfix list to close after I have chosen an item, because I'm used to the behavior of https://github.com/junegunn/fzf.vim.

Do you think this feature might be suitable for your plugin?

**Comment by yssl** [comment]
Yes, I think it would be a great option for QFEnter. How about writing your own PR for this? Contributions are always welcome.

**Comment by yssl** [comment]
New version 2.4.3 supports this feature with g:qfenter_autoclose. Thanks for suggestion!
