### ISSUE TITLE
Error when trying to make custom keymappings

### ISSUE THREAD

**Issue by guest73** [yssl/QFEnter#28]
![image](https://github.com/yssl/QFEnter/assets/4907799/98217ebf-13cc-4047-89ef-9cfc97112f48)

Getting an error when trying to make some custom mappings like this

``
let g:qfenter_exclude_filetypes = ['nerdtree', 'tagbar']
let g:qfenter_keymap = {}
let g:qfenter_keymap.cnext_keep = ['<Leader>b']

``

**Comment by yssl** [comment]
There was an issue with the exception handling code. It has now been resolved and pushed. Please pull the latest code and test it. Thanks for the report!
