### ISSUE TITLE
E154

### ISSUE THREAD

**Issue by Tuch** [yssl/QFEnter#6]
Hi, thanks for your work and please help me resolve this:
after ":helptags ~/.vim/bundle/QFEnter/doc" command
i have:
E154: Duplicate tag "g:qfenter_enable_autoquickfix" in file ~/.vim/bundle/QFEnter/doc/QFEnter.txt

**Comment by yssl** [comment]
I've just corrcted that error. It was my mistake.
Thank you for the reporting and please pull and test the new version of the doc file.
