### ISSUE TITLE
Support Location List

### ISSUE THREAD

**Issue by offero** [yssl/QFEnter#7]
I would love to use enter on things in the location list that syntastic, for example, populates. Right now QFEnter fails on the 'cc' command when pressing enter in the location list.

**Comment by yssl** [comment]
You're right. Supporting the location list must be quite useful.
I personally don't use the location list so didn't come up with the idea. I'll try it when I have available time.
Thank you for the suggestion.

**Comment by yssl** [comment]
Thanks to feix760, now QFEnter supports the location list.
